[package]
name = "pallas-validate"
version = "0.32.0"
edition = "2021"

[dependencies]
pallas-addresses = { version = "=0.32.0", path = "../pallas-addresses" }
pallas-codec = { version = "=0.32.0", path = "../pallas-codec" }
pallas-crypto = { version = "=0.32.0", path = "../pallas-crypto" }
pallas-primitives = { version = "=0.32.0", path = "../pallas-primitives" }
pallas-traverse = { version = "=0.32.0", path = "../pallas-traverse" }
rand = "0.8"
hex = "0.4"
chrono = "0.4.39"
thiserror = "1.0.49"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.122"

# phase2 dependencies
uplc = { git = "https://github.com/pragma-org/uplc.git" }
rug = { version = "1.26.1" }
itertools = "0.14.0"
tracing = "0.1.41"

[features]
phase_one = []
phase_two = []
